# Creates a deployment that defines our fulfill order app, related settings and configuration
# This deployment must be created before the service. The service references the app defined in this deployment
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fulfillorder
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fulfillorder
    spec:      
      containers:
        - name: fulfillorder
          image: torosent/fulfillorderack
          ports:
          - containerPort: 8080
          imagePullPolicy: Always
          env:
           -  name:  "MONGOURL"
              value: "mongodb://mongo-mongodb"
           -  name:  "TEAMNAME"
              value: "Team1-DWP1118"
           -  name:  "CHALLENGEAPPINSIGHTS_KEY"
              value: "2fefadc2-0f4a-475f-8279-2cd4043e1b55"
          volumeMounts:
          - mountPath: "/orders"
            name: orders
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "250m"
      volumes:
      - name: orders
        persistentVolumeClaim:
          claimName: oc2
